name: Create Diagram

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.7.1
      with:
          # A list of paths to exclude from the diagram, separated by commas.
          excluded_paths: .github,.editorconfig,.gitattributes,.gitignore,.nuget.config
